# Generated by Django 5.1 on 2025-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_listing_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='No Category Listed', max_length=100),
        ),
    ]
