# Generated by Django 5.1 on 2025-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageLink',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
